// MongoDB Update Operations for Compass
// Copy and paste these operations in MongoDB Compass

// Project 1: Blog Content Generated by AI Gemeni WP Import
db.projects.updateOne(
  { _id: ObjectId("6921ad68260694bf82d82f98") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 20000,
      allocatedExpenses: 0,
      afterExpenses: 20000,
      allocatedDisputes: 0,
      afterDisputes: 20000,
      partnerShareAmount: 0,
      finalAmount: 20000
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 2: AI Based automatic number plate recognition and vehicle detection system
db.projects.updateOne(
  { _id: ObjectId("6921ac9c260694bf82d82f94") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 800,
      allocatedExpenses: 0,
      afterExpenses: 800,
      allocatedDisputes: 0,
      afterDisputes: 800,
      partnerShareAmount: 0,
      finalAmount: 800
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 3: Library Documentation By Hassan
db.projects.updateOne(
  { _id: ObjectId("6921a763260694bf82d82f8a") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 100,
      allocatedExpenses: 0,
      afterExpenses: 100,
      allocatedDisputes: 0,
      afterDisputes: 100,
      partnerShareAmount: 0,
      finalAmount: 100
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 4: AI Sign To Text
db.projects.updateOne(
  { _id: ObjectId("6921a714260694bf82d82f86") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 468,
      allocatedExpenses: 0,
      afterExpenses: 468,
      allocatedDisputes: 0,
      afterDisputes: 468,
      partnerShareAmount: 0,
      finalAmount: 468
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 5: Customize Rocket LMS V4
db.projects.updateOne(
  { _id: ObjectId("6921a5ff260694bf82d82f54") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 315,
      allocatedExpenses: 0,
      afterExpenses: 315,
      allocatedDisputes: 0,
      afterDisputes: 315,
      partnerShareAmount: 0,
      finalAmount: 315
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 6: Limited Reps
db.projects.updateOne(
  { _id: ObjectId("6921a0c3260694bf82d82f01") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 20000,
      allocatedExpenses: 0,
      afterExpenses: 20000,
      allocatedDisputes: 0,
      afterDisputes: 20000,
      partnerShareAmount: 2000,
      finalAmount: 18000
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 7: OEM Debugging
db.projects.updateOne(
  { _id: ObjectId("69219c55260694bf82d82ed0") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 4500,
      allocatedExpenses: 0,
      afterExpenses: 4500,
      allocatedDisputes: 0,
      afterDisputes: 4500,
      partnerShareAmount: 450,
      finalAmount: 4050
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 8: AI Fine Tune Model
db.projects.updateOne(
  { _id: ObjectId("692198e9260694bf82d82ec0") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 72,
      allocatedExpenses: 0,
      afterExpenses: 72,
      allocatedDisputes: 0,
      afterDisputes: 72,
      partnerShareAmount: 7.2,
      finalAmount: 64.8
    },
    $unset: {
      afterWithdrawalFee: ""
    }
  }
);

// Project 9: Ev Charging Mobile App
db.projects.updateOne(
  { _id: ObjectId("6920e38b260694bf82d82e65") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 22500,
      allocatedExpenses: 0,
      afterExpenses: 22500,
      allocatedDisputes: 0,
      afterDisputes: 22500,
      partnerShareAmount: 2250,
      finalAmount: 20250
    },
    $unset: {
      afterWithdrawalFee: "",
      withdrawalFee: "",
      withdrawalFeeType: "",
      withdrawalFeeLocalAccount: "",
      withdrawalFeeLocalAccountType: ""
    }
  }
);

// Project 10: Fleet Dashboard
db.projects.updateOne(
  { _id: ObjectId("6920e325260694bf82d82e61") },
  {
    $set: {
      includeCharity: false,
      charityAmount: 0,
      afterCharity: 10800,
      allocatedExpenses: 0,
      afterExpenses: 10800,
      allocatedDisputes: 0,
      afterDisputes: 10800,
      partnerShareAmount: 1080,
      finalAmount: 9720
    },
    $unset: {
      afterWithdrawalFee: "",
      withdrawalFee: "",
      withdrawalFeeType: "",
      withdrawalFeeLocalAccount: "",
      withdrawalFeeLocalAccountType: ""
    }
  }
);

